In [14]:
import numpy as np

## numpy arrays

In [2]:
benimListem = [20,30,40]

In [3]:
type(benimListem)

list

In [5]:
np.array(benimListem)

array([20, 30, 40])

In [6]:
matrixListesi = [[10,20,30],[20,30,40],[30,40,50]]

In [7]:
matrixListesi[1][0]

20

In [8]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## arrange

In [12]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## zeros

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [21]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## linspace

In [27]:
np.linspace(0,20,3)

array([ 0., 10., 20.])

## eye

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## random

In [30]:
np.random.randn(4)

array([ 0.73304428, -1.35679657, -0.79614192,  0.79436417])

In [31]:
np.random.randn(4,4)

array([[-0.0529822 , -0.16152696,  0.3573557 ,  1.19871215],
       [-0.0208831 , -2.23572864, -0.44877693,  0.02989321],
       [-0.75647935,  2.13007505, -0.39546615,  0.4374374 ],
       [-1.25429716, -1.98843541, -0.70765741, -1.89296891]])

In [32]:
np.random.randint(4)

1

In [40]:
np.random.randint(1,10,2)

array([9, 4])

In [41]:
benimNumpyDizim = np.arange(30)

In [42]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [45]:
benimRandomDizim = np.random.randint(0,100,20)

In [46]:
benimRandomDizim

array([98, 75, 34, 31, 22, 35, 63, 20, 48, 50, 28, 15, 83, 63, 71, 73,  8,
       66, 80, 76])

## numpy dizi methodları

In [49]:
benimNumpyDizim.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [50]:
benimNumpyDizim.max()

29

In [51]:
benimRandomDizim.max()

98

In [52]:
benimRandomDizim.min()

8

In [53]:
benimRandomDizim.argmax()

0

In [54]:
benimRandomDizim.argmin()

16

In [55]:
benimNumpyDizim.shape

(30,)