In [1]:
import numpy as np

In [2]:
benimDizim = np.arange(0,15)

In [3]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
benimDizim[5]

5

In [5]:
benimDizim[3:5]

array([3, 4])

In [6]:
benimDizim[3::6]

array([3, 9])

In [7]:
benimDizim[::5]

array([ 0,  5, 10])

In [8]:
benimDizim[3:5] = -5

In [9]:
benimDizim

array([ 0,  1,  2, -5, -5,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
baskaDizi = np.arange(0,24)
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [13]:
slicingDizisi = baskaDizi[4:9]
slicingDizisi

array([4, 5, 6, 7, 8])

In [14]:
slicingDizisi[:] = 700

In [15]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [16]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [17]:
ornekDizi = np.arange(0,24)

In [18]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [19]:
ornekDiziKopyasi = ornekDizi.copy()
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [20]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [21]:
ornekDiziKopyasiSlicing = ornekDiziKopyasi[3:6]

In [22]:
ornekDiziKopyasiSlicing[:] = 800

In [23]:
ornekDiziKopyasiSlicing

array([800, 800, 800])

In [25]:
ornekDiziKopyasi

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [26]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## matrix

In [29]:
benimListem = [[10,20,30],[20,30,40],[40,50,60]]
benimMatrixDizim = np.array(benimListem)

In [31]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [32]:
benimMatrixDizim[0]

array([10, 20, 30])

In [33]:
benimMatrixDizim[1][2]

40

In [36]:
benimMatrixDizim[0,0]

10

In [39]:
benimMatrixDizim[2:,2:]

array([[60]])

In [44]:
 yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [45]:
yeniMatrix = np.array(yeniListe)
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
yeniMatrix[[0,2,4]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

## operasyonlar

In [50]:
yeniBirDizi = np.random.randint(1,100,20)

In [51]:
yeniBirDizi

array([51, 10, 56, 14, 10, 42, 80, 50, 58, 66,  1, 20, 63, 15, 20, 50, 97,
       27, 62, 46])

In [52]:
yeniBirDizi > 24

array([ True, False,  True, False, False,  True,  True,  True,  True,
        True, False, False,  True, False, False,  True,  True,  True,
        True,  True])

In [53]:
yeniBirDizi

array([51, 10, 56, 14, 10, 42, 80, 50, 58, 66,  1, 20, 63, 15, 20, 50, 97,
       27, 62, 46])

In [55]:
sonucDizisi=yeniBirDizi>24

In [56]:
sonucDizisi

array([ True, False,  True, False, False,  True,  True,  True,  True,
        True, False, False,  True, False, False,  True,  True,  True,
        True,  True])

In [57]:
yeniBirDizi[sonucDizisi]

array([51, 56, 42, 80, 50, 58, 66, 63, 50, 97, 27, 62, 46])

In [58]:
yeniBirDizi[yeniBirDizi>24]

array([51, 56, 42, 80, 50, 58, 66, 63, 50, 97, 27, 62, 46])

In [59]:
sonDizi = np.arange(0,24)

In [60]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [61]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [62]:
sonDizi*sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [63]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [64]:
np.max

<function numpy.amax(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)>

In [65]:
np.max(sonDizi)

23